# Generated by Django 5.0.2 on 2024-05-29 13:52

import os
from django.db import migrations
from django.contrib.auth.hashers import make_password
from users.services import UserService
from djangogramm.helpers import get_inmemory_image


path_to_resources = os.path.join(os.getcwd(), "users", "migrations", "resource")


def create_users(apps, schema_editor):
    users_data = [
        {
            "first_name": 'John',
            "last_name": 'Smith',
            "email": 'jsmith@mail.com',
            'bio': "Hi, I'm John!",
            "avatar": "1avatar.jpeg"
         },
        {
            "first_name": 'Margaret',
            "last_name": 'Thatcher',
            "email": 'mthatcher@mail.com',
            'bio': "Hi, I'm Margaret!",
        },
        {
            "first_name": 'Marie',
            "last_name": 'Curie',
            "email": 'mcurie@mail.com',
            'bio': "Hi, I'm Marie!"
        }
    ]

    User = apps.get_model("users", "CustomUser")

    for data in users_data:
        avatar = data.get('avatar')
        if avatar:
            image = get_inmemory_image(path_to_folder=path_to_resources, file_name=avatar)
            User.objects.create(
                first_name=data['first_name'],
                last_name=data['last_name'],
                email=data['email'],
                is_active=True,
                activation_link=UserService.generate_activation_link(),
                bio=data['bio'],
                password=make_password('8uhb5thm'),
                avatar=image
            )
        else:
            User.objects.create(
                first_name=data['first_name'],
                last_name=data['last_name'],
                email=data['email'],
                is_active=True,
                activation_link=UserService.generate_activation_link(),
                bio=data['bio'],
                password=make_password('8uhb5thm')
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
