# Generated by Django 4.2.10 on 2024-05-30 17:32

from django.db import migrations
from ..services import PostService
from ..models import Image


def create_posts(apps, schema_editor):

    posts_data = [
        {
            "user_id": 1,
            "body": 'Iceland, Reykjavik!',
            "tags": ['#iceland', '#weather'],
            "images": ["images/iceland.jpeg", "images/iceland2.jpeg", "images/iceland3.jpeg", "images/iceland4.jpeg"]
         },
        {
            "user_id": 3,
            "body": 'Italian food...',
            "tags": ['#traveling', '#vacation'],
            "images": ["images/italy_food.jpeg"]
        },
        {
            "user_id": 2,
            "body": 'My flowers!',
            "tags": ['#flowers'],
            "images": ["images/flowers4.jpeg", "images/flowers5.jpeg", "images/flowers6.jpeg"]
        },
        {
            "user_id": 1,
            "body": 'More Iceland!!',
            "tags": ['#iceland', '#architecture'],
            "images": ["images/iceland5.jpeg", "images/iceland6.jpeg", "images/iceland7.jpeg", "images/iceland8.jpeg",
                       "images/iceland9.jpeg"]
         },
        {
            "user_id": 2,
            "body": 'Flowers!',
            "tags": ['#flowers'],
            "images": ["images/flowers.jpeg", "images/flowers2.jpeg", "images/flowers3.jpeg"]
        },
        {
            "user_id": 3,
            "body": 'i love painting...',
            "tags": ['#painting'],
            "images": ["images/painting.jpeg"]
        },
        {
            "user_id": 2,
            "body": 'Italy!',
            "tags": ['#italy', '#traveling'],
            "images": ["images/italy1.jpeg", "images/italy2.jpeg", "images/italy3.jpeg", "images/italy4.jpeg",
                       "images/italy5.jpeg"]
        },
        {
            "user_id": 2,
            "body": 'Poland!',
            "tags": ['#poland', '#traveling'],
            "images": ["images/poland.jpeg", "images/poland2.jpeg"]
        }
    ]

    for post_data in posts_data:
        post = PostService.create_post(user_id=post_data['user_id'], body=post_data['body'], tags=post_data['tags'])
        for image in post_data['images']:
            Image.objects.create(image=image, post_id=post.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('users', '0002_create_users'),
        ('feed', '0001_initial'),
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_posts),
    ]
