# Generated by Django 5.0.2 on 2024-05-29 13:52

from django.db import migrations
from django.contrib.auth.hashers import make_password
from users.services import UserService


def create_users(apps, schema_editor):
    users_data = [
        {
            "first_name": 'John',
            "last_name": 'Smith',
            "email": 'jsmith@mail.com',
            'bio': "Hi, I'm John!",
            "avatar": "avatars/1avatar.jpeg"
         },
        {
            "first_name": 'Margaret',
            "last_name": 'Thatcher',
            "email": 'mthatcher@mail.com',
            'bio': "Hi, I'm Margaret!",
            "avatar": "avatars/2avatar.jpeg"
        },
        {
            "first_name": 'Marie',
            "last_name": 'Curie',
            "email": 'mcurie@mail.com',
            'bio': "Hi, I'm Marie!"
        }
    ]

    User = apps.get_model("users", "CustomUser")

    for data in users_data:
        User.objects.create(
            first_name=data['first_name'],
            last_name=data['last_name'],
            email=data['email'],
            is_active=True,
            activation_link=UserService.generate_activation_link(),
            bio=data['bio'],
            password=make_password('8uhb5thm'),
            avatar=data.get('avatar')
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
