# Generated by Django 4.2.10 on 2024-05-30 17:32

import os
from django.db import migrations
from djangogramm.helpers import get_inmemory_image
from feed.services import PostService
from feed.models import Image, AuthorFollower, Like


path_to_resources = os.path.join(os.getcwd(), "feed", "migrations", "resource")


def create_posts(apps, schema_editor):

    inmemory_image_1 = get_inmemory_image(path_to_folder=path_to_resources, file_name="poland.jpeg")
    inmemory_image_2 = get_inmemory_image(path_to_folder=path_to_resources, file_name="poland2.jpeg")

    first_post_data = {
            "user_id": 1,
            "body": 'Iceland, Reykjavik!',
            "tags": ['#iceland', '#weather']
         }
    post = PostService.create_post(user_id=first_post_data['user_id'], body=first_post_data['body'],
                                   tags=first_post_data['tags'])
    image_1 = Image.objects.create(image=inmemory_image_1, post_id=post.pk)
    image_2 = Image.objects.create(image=inmemory_image_2, post_id=post.pk)

    other_posts_data = [
        {
            "user_id": 3,
            "body": 'Italian food...',
            "tags": ['#traveling', '#vacation'],
            "images": [image_1.image]
        },
        {
            "user_id": 2,
            "body": 'My flowers!',
            "tags": ['#flowers'],
            "images": [image_1.image, image_2.image, image_1.image]
        },
        {
            "user_id": 1,
            "body": 'More Iceland!!',
            "tags": ['#iceland', '#weather', '#architecture'],
            "images": [image_1.image, image_2.image, image_1.image, image_2.image, image_1.image]
         },
        {
            "user_id": 2,
            "body": 'Flowers!',
            "tags": ['#flowers'],
            "images": [image_1.image, image_2.image, image_1.image, image_2.image]
        },
        {
            "user_id": 3,
            "body": 'i love painting...',
            "tags": ['#painting'],
            "images": [image_1.image],
            "likes": [1, 2]
        },
        {
            "user_id": 2,
            "body": 'Italy!',
            "tags": ['#italy', '#traveling'],
            "images": [image_1.image, image_2.image, image_1.image, image_2.image, image_1.image],
            "likes": [1]
        },
        {
            "user_id": 2,
            "body": 'Poland!',
            "tags": ['#poland', '#traveling', '#morskieoko'],
            "images": [image_1.image, image_2.image],
            "likes": [1, 3]
        }
    ]

    for post_data in other_posts_data:
        post = PostService.create_post(user_id=post_data['user_id'], body=post_data['body'], tags=post_data['tags'])
        likes = post_data.get('likes')
        if likes:
            for like in likes:
                Like.objects.create(post_id=post.pk, user_id=like)

        for image in post_data['images']:
            Image.objects.create(image=image, post_id=post.pk)


def create_followers(apps, schema_editor):

    authors_followers = [
        (1, 2),
        (1, 3),
        (2, 1),
        (2, 3),
        (3, 1)
    ]

    for author_follower in authors_followers:
        author, follower = author_follower
        AuthorFollower.objects.create(author_id=author, follower_id=follower)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('users', '0002_create_users'),
        ('feed', '0001_initial'),
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_posts),
        migrations.RunPython(create_followers),
    ]
